version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gpak#1234
      POSTGRES_DB: mapmytripdb
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on: [db]
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mapmytripdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Gpak#1234
    ports: ["8080:8080"]

volumes:
  pgdata:
